#!/usr/bin/env python
"""
encrypt

Usage:
    encrypt <filename>
"""
import os, sys
from md5 import md5
from Crypto.Cipher import AES
from Crypto import Random
from getpass import getpass

def getkey(password=None, iv=''):
    return md5(str(iv) + str(password)).hexdigest()[:32]

def encrypt(message, password):
    """Encrypts a message with `key`"""
    Random.atfork()
    IV = Random.new().read(AES.block_size)
    key = getkey(password, IV)
    cipher = AES.new(key, AES.MODE_CFB, IV)
    key = getkey(Random.new().read(AES.block_size))
    return str(IV) + str(cipher.encrypt(message))

def get_password(confirm=False):
    password = getpass("Password: ")
    while confirm is True:
        conf = getpass("Confirm: ")
        if conf == password:
            confirm = False
        else:
            print("Passwords do not match!")
            password = getpass("Password: ")
    return password

if __name__ == "__main__":
    try:
        message = sys.argv[1]
        if os.path.exists(message):
            """It's actually a file"""
            with open(message, 'rb') as fd:
                data = fd.read()
            message = data
        password = get_password(True)
        result = encrypt(message, password)
        outfile = sys.argv[2]
        with open(outfile, 'wb') as fd:
            fd.write(result)

    except IndexError:
        print("Specify a message or file to encrypt")
        
